# ==============================================================================
# Device: Guest Living Room Mini-Split
# ==============================================================================
substitutions:
  name: ac_guest_living_room
  friendly_name: "Guest Living Room AC"
  follow_me_sensor: "sensor.guest_living_room_temperature"

packages:
  base_config: !include packages/slwf-base.yaml
